apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxOTIuMTY4LjU2LjI1MDo5MDkxIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InJlZGhhdCIsImF1dGgiOiJZV1J0YVc0NmNtVmthR0YwIn19fQ==
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
